config/routes.rb
Rails.application.routes.draw do
  # TODO: don't keep index
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show, :index]
  resources :profiles, only: [:create, :edit, :update]
  
  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :index, :update]
    resources :friendships, only: [:create, :show, :destroy]
    resource :current_user, only: [:show]
    resources :posts, only: [:create, :show, :destroy] # Add edit functionality later
    resources :comments, only: [:create, :show, :destroy]
    resources :images, only: [:create, :show, :destroy, :update]
    resources :post_likes, only: [:create, :destroy]
    resources :comment_likes, only: [:create, :destroy]
  end
  
  root to: "static_pages#root"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :comment_likes
  
  validates :body, :user_id, :post_id, presence: true
end

app/models/comment_like.rb
class CommentLike < ActiveRecord::Base
  belongs_to :user
  validates :comment_id, :user_id, presence: true
  validates :comment_id, uniqueness: { scope: :user_id }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :in_friend, class_name: "User", foreign_key: :in_friend_id
  belongs_to :out_friend, class_name: "User", foreign_key: :out_friend_id
  
  validates :in_friend_id, :out_friend_id, :presence => true
  validates :out_friend_id, :uniqueness => { :scope => :in_friend_id }
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  validates :file_url, :user_id, presence: true  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :post_likes
  
  validates :body, :user_id, presence: true
end

app/models/post_like.rb
class PostLike < ActiveRecord::Base
  belongs_to :user
  validates :post_id, :user_id, presence: true
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  validates :first_name, :last_name, :user_id, presence: true
  validates :user_id, uniqueness: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  
  has_one :profile
  has_many :out_friendships, class_name: "Friendship", foreign_key: :out_friend_id
  has_many :in_friendships, class_name: "Friendship", foreign_key: :in_friend_id
  has_many :posts
  has_many :comments
  has_many :images
  has_many :post_likes
  has_many :comment_likes
  
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  # TODO: fix broken length check
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  def password=(secret)
    self.password_digest = BCrypt::Password.create(secret)
  end
  
  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
  
  def friendRequests
    users = []
    self.in_friendships.each do |in_friendship|
      user = User.find(in_friendship.out_friend_id)
      users << user unless self.connectedFriends.include?(user)
    end
    users
  end
  
  def connectedFriends
    users = []
    self.out_friendships.each do |out_friendship|
      match = self.in_friendships.select do |in_friendship|
        out_friendship.in_friend_id == in_friendship.out_friend_id
      end.first
      users << User.find(match.out_friend_id) if match
    end
    users
  end
  
  def sentRequests
    users = []
    self.out_friendships.each do |out_friendship|
      user = User.find(out_friendship.in_friend_id)
      users << user unless self.connectedFriends.include?(user)
    end
    users
  end
  
  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  def login_required
    redirect_to new_user_url if !signed_in?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :login_required, only: :create
  
  def create
    @friendship = Friendship.new(friendship_params)
    if @friendship.save

      render json: @friendship
    end
  end

  private
  def friendship_params
    params.require(:friendship).permit(:in_friend_id, :out_friend_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :login_required, only: :update
  
  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(profile_params)
      render json: @profile
    else
      render json: @profile.errors.full_messages, status: :unprocessable_entity
    end
  end
  
  private
  def profile_params
    params.require(:profile).permit(
      :first_name,
      :last_name,
      :bio
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])
    if @user
      login!(@user)
      redirect_to root_url
    else
      flash[:errors] = ["Wrong email or password"]
      redirect_to :back
    end
  end
  
  def new
    if signed_in?
      redirect_to root_url
    else
      @user = User.new
      render :new
    end
  end
  
  def destroy
    logout!
    redirect_to new_user_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, only: :show
  
  def create
    @user = User.new(user_params)
    @profile = Profile.new(profile_params)
    @user.profile = @profile
    
    
    if @user.save
      if @profile.save
        login!(@user)
        redirect_to root_url
      else
        flash.now[:errors] = ["Email already taken"]
        render :new
      end
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def new
    if signed_in?
      redirect_to root_url
    else
      @user = User.new
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    redirect_to "/#/users/#{params[:id]}"
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
  
  def profile_params
    # Apparently rails associates foreign key user_id automatically
    params.require(:profile).permit(
      :first_name,
      :last_name,
      :name_tag,
      :bio
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login!(user)
    session[:session_token] = user.reset_session_token!
    cookies[:facedoge_session_token] = session[:session_token]
    @current_user = user
  end
  
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    cookies[:current_user] = 0
  end
  
  def current_user
    @current_user || User.find_by_session_token(session[:session_token])
  end
  
  def signed_in?
    !!(current_user)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <ul class="nav navbar-nav">
      
    <% if signed_in? %>
      <p class="navbar-text">Signed in as <%= current_user.profile.first_name %></p>
      <li class="dropdown">
        <a class="dropdown-toggle" type="button" id="options" data-toggle="dropdown">
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="options">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="/#/users/all">All Users</a></li>
          <li><%= link_to "My Profile", user_url(current_user), method: :get %></li>
          <li><%= link_to "Sign out", session_url, method: :delete %></li>
        </ul>
      </li>
      
      
    <% else %>
    
      <form class="navbar-form navbar-left" action="/session" method="POST">
        <div class="form-group">
          <input type="text" name="user[email]" class="form-control" placeholder="Email">
        </div>
        <div class="form-group">
          <input type="password" name="user[password]" class="form-control" placeholder="Password">
        </div>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="submit" class="btn btn-default">Log In</button>
      </form>
      
      
      
    <% end %>
    
    </ul>
  </div>
  
  

  <div class="pull-right">
    <ul class="nav navbar-nav nav-cushion">
      <li><a class="navbar-brand" href="/#"><%= image_tag("logo-xs.png") %></a></li>
    </ul>
  </div>
</nav>
<br><br><br>
<div class="alerts">
<% if flash[:errors] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
     <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <%= flash[:errors].join(", ") %>
  </div>
<% end %>
</div>
<br><br>

app/views/layouts/_sidebar.html.erb
<nav class="navbar affix sidebar-list" role="navigation">
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facedoge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <script type="text/javascript" src="http://api.filepicker.io/v1/filepicker.js"></script>
  <script>
    filepicker.setKey("APfLg3iZUTanSEgY5zAsNz");
  </script>
  
  <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="header">
    <%= render "layouts/header" %>
  </div>
  
  <div class="midsection">
      <% if signed_in? %>
      <div id="sidebar-wrapper">
        <div class="sidebar">
          <%= render "layouts/sidebar" %>
        </div>
      </div>
      <% else %>
        <img class="splash" src="/assets/splash.png">
      <% end %> 
      <div id="content-wrapper">
        <div class="content">
          <%= yield %>
        </div>
      </div>
  </div>
  
  <% if !signed_in? %>
    <div class="footer">
    </div>
  <% end %>
  
</body>

<div id="preload">
  <img class="loading" src="/assets/loading.gif">
</div>

</html>